In [2]:
from pyenspp import schaake_shuffle
import numpy as np

# example data in 《The schaake shuffle: A method for reconstructing space–time variability in forecasted precipitation and temperature fields》
x = np.array([15.3, 11.2, 8.8, 11.9, 7.5, 9.7, 8.3, 12.5, 10.3, 10.1])
y = np.array([10.7, 9.3, 6.8, 11.3, 12.2, 13.6, 8.9, 9.9, 11.8, 12.9])
print('1-dimensional:')
print(x, '\n', y, '\n', schaake_shuffle(x,y,axis=0))

X = np.array([
[7.5, 8.3, 8.8, 9.7, 10.1, 10.3, 11.2, 11.9, 12.5, 15.3],
[6.3, 7.2, 7.5, 7.9, 8.6, 9.3, 11.8, 12.2, 13.5, 17.7],
[12.4, 13.5, 14.2, 14.5, 15.6, 15.9, 16.3, 17.6, 18.3, 23.9]
])
Y = np.array([
    [10.7, 9.3, 6.8, 11.3, 12.2, 13.6, 8.9, 9.9, 11.8, 12.9],
    [10.9, 9.1, 7.2, 10.7, 13.1, 14.2, 9.4, 9.2, 11.9, 12.5],
    [13.5, 13.7, 9.3, 15.6, 17.8, 19.3, 12.1, 11.8, 15.2, 16.9]
])
print('2-dimensional:')
print(X, '\n', Y, '\n', schaake_shuffle(X,Y,axis=1))

1-dimensional:
[15.3 11.2  8.8 11.9  7.5  9.7  8.3 12.5 10.3 10.1] 
 [10.7  9.3  6.8 11.3 12.2 13.6  8.9  9.9 11.8 12.9] 
 [10.1  8.8  7.5 10.3 11.9 15.3  8.3  9.7 11.2 12.5]
2-dimensional:
[[ 7.5  8.3  8.8  9.7 10.1 10.3 11.2 11.9 12.5 15.3]
 [ 6.3  7.2  7.5  7.9  8.6  9.3 11.8 12.2 13.5 17.7]
 [12.4 13.5 14.2 14.5 15.6 15.9 16.3 17.6 18.3 23.9]] 
 [[10.7  9.3  6.8 11.3 12.2 13.6  8.9  9.9 11.8 12.9]
 [10.9  9.1  7.2 10.7 13.1 14.2  9.4  9.2 11.9 12.5]
 [13.5 13.7  9.3 15.6 17.8 19.3 12.1 11.8 15.2 16.9]] 
 [[10.1  8.8  7.5 10.3 11.9 15.3  8.3  9.7 11.2 12.5]
 [ 9.3  7.2  6.3  8.6 13.5 17.7  7.9  7.5 11.8 12.2]
 [14.5 15.6 12.4 16.3 18.3 23.9 14.2 13.5 15.9 17.6]]


In [4]:
from pyenspp import schaake_shuffle_block
import numpy as np

X = np.array([
[7.5, 8.3, 8.8, 9.7, 10.1, 10.3, 11.2, 11.9, 12.5, 15.3],
[6.3, 7.2, 7.5, 7.9, 8.6, 9.3, 11.8, 12.2, 13.5, 17.7],
[12.4, 13.5, 14.2, 14.5, 15.6, 15.9, 16.3, 17.6, 18.3, 23.9]
])
Y = np.array([
    [10.7, 9.3, 6.8, 11.3, 12.2, 13.6, 8.9, 9.9, 11.8, 12.9],
    [10.9, 9.1, 7.2, 10.7, 13.1, 14.2, 9.4, 9.2, 11.9, 12.5],
    [13.5, 13.7, 9.3, 15.6, 17.8, 19.3, 12.1, 11.8, 15.2, 16.9]
])
print('2-dimensional:(Using block shuffle)')
print(X, '\n', Y, '\n', schaake_shuffle_block(X.T,Y.T,axis=0).T)

2-dimensional:(Using block shuffle)
[[ 7.5  8.3  8.8  9.7 10.1 10.3 11.2 11.9 12.5 15.3]
 [ 6.3  7.2  7.5  7.9  8.6  9.3 11.8 12.2 13.5 17.7]
 [12.4 13.5 14.2 14.5 15.6 15.9 16.3 17.6 18.3 23.9]] 
 [[10.7  9.3  6.8 11.3 12.2 13.6  8.9  9.9 11.8 12.9]
 [10.9  9.1  7.2 10.7 13.1 14.2  9.4  9.2 11.9 12.5]
 [13.5 13.7  9.3 15.6 17.8 19.3 12.1 11.8 15.2 16.9]] 
 [[10.1  8.8  7.5 10.3 11.9 15.3  8.3  9.7 11.2 12.5]
 [ 9.3  7.2  6.3  8.6 13.5 17.7  7.9  7.5 11.8 12.2]
 [14.5 15.6 12.4 16.3 18.3 23.9 14.2 13.5 15.9 17.6]]
